### ISSUE TITLE
Add toolbar on/off addon icon

### ISSUE THREAD

**Issue by Draxler** [jpatters/tp-beacon#8]
Is there any chance to add toolbar on/off addon icon.. simple click on addon icon would turn off this addon and icon it self could turn in black and white color (when off). And when addon is turned off then another simple click on this addon icon would turn addon back on and icon would get its colors back when turn on again.. :)   I think this would give this addon big userfriendley asset.. 
And btw, i'm happy to see you apdeted this addon also for another trackers..

**Comment by Draxler** [comment]
Yea, it's realy good idea.. :)  I need that turn ON & OFF switch badly.. Its good addon but it need to be swithed Off a lot of times. Any chance this addon get a browser icon with Toggle On & Off option anytime soon ? :)

**Comment by jpatters** [comment]
Thanks for reminding me of this. When the pirate bay went down i kind of just forgot about this. I'll try and get it done shortly

**Comment by Draxler** [comment]
:+1:   Waoouu , This was quick . :smile:

**Comment by jpatters** [comment]
By shortly I mean within the next week. Are you on Chrome?

**Comment by Draxler** [comment]
Yes i know,, i meant It was quick reply :smile:  
i'm using FF ..

**Comment by jpatters** [comment]
Just updated. It will have to go through the review process, but if you want it right away you can use the view other versions link (https://addons.mozilla.org/en-US/firefox/addon/the-pirate-beacon/versions/) and download the latest one.
let me know if there are any issues.

**Comment by Draxler** [comment]
It's working realy nice. If there be any additional issues i'll let you know..
